language: generic
sudo: required
services:
  - docker

before_install:
  - gem install bundler
  - docker build -t leotn/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true leotn/react-test npm run test

after_success:
  - docker build -t leotn/multi-client ./client
  - docker build -t leotn/multi-nginx ./nginx
  - docker build -t leotn/multi-server ./server
  - docker build -t leotn/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push to dockerhub
  - docker push leotn/multi-client
  - docker push leotn/multi-nginx
  - docker push leotn/multi-server
  - docker push leotn/multi-worker
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-677439251017"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"